import type { Metadata } from "next";
import JsonLd from "@/components/JsonLd";
import { breadcrumbJsonLd, buildMetadata, webPageJsonLd } from "@/lib/seo";

export const metadata: Metadata = buildMetadata("privacy");

export default function PrivacyPage() {
  return (
    <main id="main">
      <JsonLd
        data={[
          webPageJsonLd("privacy"),
          breadcrumbJsonLd([
            { name: "Home", path: "/" },
            { name: "Privacy policy", path: "/privacy" },
          ]),
        ]}
      />
      <div className="phead">
        <div className="wrap narrow">
          <p className="label">Legal</p>
          <h1>Privacy policy</h1>
          <p className="lede">
            How OLL collects, uses, shares and protects information when you use our platform, take an assessment, or
            nominate someone else to take one.
          </p>
          <div className="meta-row">
            <span>Last updated: [date]</span>
            <span>
              Applies to: platform.ollacademy.com, theorganizationlearninglabs.com and research.ollacademy.com
            </span>
          </div>
        </div>
      </div>

      <section>
        <div className="wrap legal">
          <nav className="toc" aria-label="On this page">
            <h4>On this page</h4>
            <a href="#who">1. Who we are</a>
            <a href="#collect">2. What we collect</a>
            <a href="#why">3. Why we use it</a>
            <a href="#results">4. Who sees assessment results</a>
            <a href="#aggregate">5. Aggregated insight</a>
            <a href="#share">6. Sharing and processors</a>
            <a href="#cookies">7. Cookies</a>
            <a href="#retention">8. Retention</a>
            <a href="#security">9. Security</a>
            <a href="#rights">10. Your rights</a>
            <a href="#transfers">11. International transfers</a>
            <a href="#children">12. Age</a>
            <a href="#changes">13. Changes</a>
            <a href="#contact">14. Contact and grievances</a>
          </nav>

          <div className="legal-body">
            <div className="note">
              <p>
                <span className="flag">Draft for legal review</span> This policy is written to match how the platform
                actually works, but it has not been reviewed by counsel. Items in square brackets need your legal
                entity details before publication.
              </p>
            </div>

            <h2 id="who">1. Who we are</h2>
            <p>
              This policy is issued by <strong>[Registered entity name]</strong> (&quot;OLL&quot;, &quot;we&quot;,
              &quot;us&quot;), registered at [registered address], Bengaluru, India. We operate the OLL platform, the
              OLL Research library and this website.
            </p>
            <p>
              Where your employer nominates you for an assessment, that employer is the party deciding to run the
              assessment and we process your information to deliver it. Where you sign up on your own, we decide how
              your information is processed for that purpose.
            </p>

            <h2 id="collect">2. What we collect</h2>
            <h3>Information you give us</h3>
            <ul>
              <li>
                <strong>Account details:</strong> name, work email, password, organization name.
              </li>
              <li>
                <strong>Role context:</strong> current job role, function, department, industry and sub-industry, the
                role you are developing towards, and any profiling answers the assessment needs.
              </li>
              <li>
                <strong>Assessment responses:</strong> your answers to scenario, multiple-choice, ranking and task
                questions.
              </li>
              <li>
                <strong>Goals and development inputs:</strong> priorities you set, progress you record, and anything
                you submit in the course of a development activity.
              </li>
              <li>
                <strong>Contact and enquiry information:</strong> what you send us by form, email or phone.
              </li>
            </ul>
            <h3>Information generated by use</h3>
            <ul>
              <li>
                <strong>Results and outputs:</strong> competency scores, gap bands, capability signatures and your
                Development Action Plan.
              </li>
              <li>
                <strong>Usage data:</strong> pages and features used, time taken, device and browser type, approximate
                location derived from IP address, and log data needed to keep the service secure.
              </li>
            </ul>
            <p>
              We collect what the diagnostic requires and no more. We do not ask for special category data such as
              health, religion or biometric information, and you should not submit it.
            </p>

            <h2 id="why">3. Why we use it</h2>
            <ul>
              <li>
                To create and administer your account and deliver the assessment relevant to your role and industry.
              </li>
              <li>
                To produce your results and Development Action Plan, and to support you in interpreting them.
              </li>
              <li>
                To report progress and completion to the organization that nominated you, where it has authorized the
                assessment.
              </li>
              <li>
                To produce aggregated capability and readiness insight for that organization, as described in section
                5.
              </li>
              <li>To improve the assessment architecture, our research and the platform itself.</li>
              <li>To keep the service secure, prevent misuse and meet our legal obligations.</li>
            </ul>
            <p>
              Where the law requires a legal basis, we rely on the performance of a contract with you or your
              organization, our legitimate interests in operating and improving the service, your consent where we ask
              for it, and compliance with legal obligations.
            </p>

            <h2 id="results">4. Who sees assessment results</h2>
            <div className="callout">
              <p>
                An individual&apos;s full results and Development Action Plan are not shared with an employer
                automatically. Sharing them requires the participant&apos;s consent and follows the organization&apos;s
                own policy.
              </p>
            </div>
            <ul>
              <li>
                <strong>The participant</strong> sees their full results and their Development Action Plan.
              </li>
              <li>
                <strong>OLL assessment staff</strong> access results where needed to deliver, support and quality-assure
                the assessment.
              </li>
              <li>
                <strong>The nominating organization</strong> receives progress and completion updates where it has
                authorized the assessment, and aggregated insight as described below.
              </li>
            </ul>
            <p>
              A single participant&apos;s result is an individual-level perspective. It is not a measure of the whole
              organization and we do not present it as one.
            </p>

            <h2 id="aggregate">5. Aggregated insight</h2>
            <p>
              Department and organization views are built from authorized, aggregated results. We design these views so
              that individual results cannot reasonably be identified from them, including by applying a minimum group
              size before a breakdown is shown. Where a group is too small to aggregate safely, the view is withheld
              rather than published.
            </p>

            <h2 id="share">6. Sharing and processors</h2>
            <p>
              We do not sell personal information and we do not share it for advertising. We share it only:
            </p>
            <ul>
              <li>with the organization that nominated you, to the extent described in section 4;</li>
              <li>
                with service providers who process information on our instructions, under contract, for hosting, email,
                analytics, support and payments: <strong>[list of current processors]</strong>;
              </li>
              <li>
                where required by law, regulation or valid legal process, or to protect the rights and safety of users
                and the public;
              </li>
              <li>
                in connection with a corporate transaction, where the recipient is bound by terms no less protective
                than these.
              </li>
            </ul>

            <h2 id="cookies">7. Cookies</h2>
            <p>
              We use cookies and similar technologies that are strictly necessary to run the service, to remember your
              preferences, and to understand how the platform is used so we can improve it. You can control
              non-essential cookies through your browser or, where offered, our cookie banner.{" "}
              <span className="flag">Confirm the analytics and marketing tools in use before publication</span>
            </p>

            <h2 id="retention">8. Retention</h2>
            <p>
              We keep account and assessment information for as long as your account is active and for{" "}
              <strong>[retention period]</strong> after it closes, so that development progress remains meaningful
              over time and so we can meet legal and contractual obligations. Aggregated and de-identified information
              may be kept for longer for research purposes. You may ask us to delete your information as set out in
              section 10.
            </p>

            <h2 id="security">9. Security</h2>
            <p>
              We use access controls, encryption in transit, segregation of assessment content and results, and
              internal review of who may view identifiable results. No system is completely secure, but we work to
              limit both the likelihood and the impact of an incident, and we will notify affected users and
              authorities where the law requires it.
            </p>

            <h2 id="rights">10. Your rights</h2>
            <p>
              Depending on where you are, you may have the right to access the information we hold about you, to
              correct it, to ask for it to be deleted, to withdraw a consent you previously gave, to object to or
              restrict certain processing, and to receive a copy in a portable form.
            </p>
            <p>
              Under India&apos;s Digital Personal Data Protection Act, 2023 you may also nominate another person to
              exercise your rights in the event of death or incapacity, and you may raise a grievance with us using the
              contact details below. Where the General Data Protection Regulation applies to you, you may also lodge a
              complaint with your supervisory authority.
            </p>
            <p>
              To exercise any of these, write to us at <strong>[privacy email]</strong>. Where your employer nominated
              you for an assessment, we may direct part of your request to them.
            </p>

            <h2 id="transfers">11. International transfers</h2>
            <p>
              We operate from India and may use service providers located elsewhere. Where information moves across
              borders, we put appropriate safeguards in place, including contractual protections with those providers.{" "}
              <span className="flag">Confirm hosting regions and transfer mechanism</span>
            </p>

            <h2 id="children">12. Age</h2>
            <p>
              The platform is intended for working professionals and is not directed at children. We do not knowingly
              collect information from anyone under 18. If you believe a minor has provided information, contact us
              and we will delete it.
            </p>

            <h2 id="changes">13. Changes</h2>
            <p>
              We may update this policy as the platform changes. We will post the revised version here with a new date
              and, where the change is significant, notify account holders directly.
            </p>

            <h2 id="contact">14. Contact and grievances</h2>
            <p>
              For any question about this policy, or to raise a grievance about how your information has been handled:
            </p>
            <ul>
              <li>
                <strong>Email:</strong> [privacy email]
              </li>
              <li>
                <strong>Grievance officer:</strong> [name and designation]
              </li>
              <li>
                <strong>Phone:</strong> +91 76766 46518
              </li>
              <li>
                <strong>Post:</strong> [registered address], Bengaluru, India
              </li>
            </ul>
            <p>
              We aim to acknowledge a grievance within [x] working days and to resolve it within the period required by
              applicable law.
            </p>
          </div>
        </div>
      </section>
    </main>
  );
}
